### ISSUE TITLE
OBS v28 crashes immediately upon launch

### ISSUE THREAD

**Issue by lcalder** [nhielost/obs-midi-mg#11]
I just tried the obs-midi-mg-1.2.2-windows-x64.zip plugin

As soon as I launch OBS v28 it crashes before OBS can open a single window, offering to save a crash log.
I have attached a crash log as well as a regular log file.

Please help.
Thanks so much.
[Crash 2022-09-05 01-50-26.txt](https://github.com/nhielost/obs-midi-mg/files/9488291/Crash.2022-09-0
[2022-09-05 01-50-19.txt](https://github.com/nhielost/obs-midi-mg/files/9488296/2022-09-05.01-50-19.txt)
5.01-50-26.txt)

**Comment by datlaunchystark** [comment]
Your links to your logs don't work can you reupload them?

**Comment by lcalder** [comment]
It says to drag and drop... I'll try again

[2022-09-05 01-50-19.txt](https://github.com/nhielost/obs-midi-mg/files/9488397/2022-09-05.01-50-19.txt)

[Crash 2022-09-05 01-50-26.txt](https://github.com/nhielost/obs-midi-mg/files/9488415/Crash.2022-09-05.01-50-26.txt)

**Comment by datlaunchystark** [comment]
Ok just curious is it just OBS using the MIDI device and does it do the same thing with the device disconnected?  If so it sounds like an issue I am currently having when another program is using a MIDI device on my system which I mentioned on https://github.com/nhielost/obs-midi-mg/issues/10 and https://github.com/nhielost/obs-midi-mg/issues/8.  That crash is also on startup.

The developer said that "it will take time to fix as I have to reroute certain aspects of the program, but this will be fixed by the next update."

**Comment by lcalder** [comment]
It's a bit complicated. I have several physical midi devices and I use many pieces of midi software simultaneously, including OBS. So I have BOME Midi Software that maps the physical devices to virtual ports, which will allow multiple programs simultaneous access.
It has worked pretty seamlessly for the last two years and I have used at least 20 programs, including plugins, simultaneously, and without problems.
I have attached my OBS v27 logs and you will see that the only midi ports OBS is looking at are the Virtual Ports 1, 2 and 3. I've attached a screenshot of the BOME routing of physical devices to virtual devices.
I have never gotten a chance to see your software in action since it doesn't run on OBS v27, and have never gotten past the crash screen in OBS v28 when your plugin is installed. When I remove the dll from the obs plugins directory, OBS v28 launches fine.
I originally installed a fresh portable install of OBS v28 and only your plugin and it still crashed.
The log I sent you obviously has a bunch of other plugins installed, but they load ok when yours is removed.

I've attached a recent log of my OBS v27 which shows the virtual midi ports being loaded...

<img width="765" alt="ppInk_SRLmM61fFy" src="https://user-images.githubusercontent.com/50305507/188423527-9b194d58-ff19-4c3b-8ecb-a3d29f84f42c.png">

[2022-09-04 08-39-04.txt](https://github.com/nhielost/obs-midi-mg/files/9488835/2022-09-04.08-39-04.txt)

**Comment by datlaunchystark** [comment]
OK yeah that does sound like issue https://github.com/nhielost/obs-midi-mg/issues/8 to me as the BONE MIDI Software is using some of the MIDI Devices and routing them to virtual MIDI ports as the logs look very similar to mine and others.  The bug is the plugin tries to activate every MIDI device on the system and if one fails to activate, OBS will crash.  The developer is looking into this issue already and hopefully it will be fixed by the next update.

**Comment by Willsie-Digital** [comment]
I am having the same issue with v1.2.2 without BOME midi installed. I only have an Akai LPD8. It appears to crash when trying to open the LPD8. 

The LPD8 is being used by Voicemeeter. When I remove the LPD8 from Voicemeeter the plugin works.

I think the plugin needs to be able handle when a device cannot be opened.

Crash log and Normal Log Attached when LPD8 is in use by VoiceMeeter:
[Crash 2022-09-05 17-08-01.txt](https://github.com/nhielost/obs-midi-mg/files/9492284/Crash.2022-09-05.17-08-01.txt)
[2022-09-05 17-07-56.txt](https://github.com/nhielost/obs-midi-mg/files/9492285/2022-09-05.17-07-56.txt)


Normal Log Attached, when LPD8 is not in use by VoiceMeeter:
[2022-09-05 17-15-31.txt](https://github.com/nhielost/obs-midi-mg/files/9492287/2022-09-05.17-15-31.txt)

**Comment by nhielost** [comment]
The newest update (v1.3.0) has addressed this issue. If this issue persists, please create a new issue for that update.

Again, thanks for the feedback!
