### ISSUE TITLE
cant record midi inputs with arturia minilab mk2

### ISSUE THREAD

**Issue by dalwnn** [nhielost/obs-midi-mg#114]
i've installed the plugin, tried to input some keybinds using the pads on my synth but the plug seems to refuse the keystroke, it's just not recording them, any idea? Do i have to set up my pad prior to using the plug?

**Comment by nhielost** [comment]
Hello!

Does the plugin recognize that the device is connected to your system? If so, it should be listed somewhere under the *MIDI Devices* menu. If not, this either means the device is not connected at all, or there is an issue with the device that's causing it to not show up there.

If the plugin does list your device in that menu, click on it and make sure that it is allowed to receive input messages. The input button should be enabled here so that the plugin can communicate with that device. If this button is enabled and your bindings are still not working, please let me know.

Hope this helps!

**Comment by dalwnn** [comment]
well apparantly it was my minilab mk2 that wasnt correctly linked to my pc, it's now working all right, ty still!

**Comment by nhielost** [comment]
No problem!
